version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=webapp
      - POSTGRES_PASSWORD=Iu62p46hLnXosIAyPhhP
      - POSTGRES_DB=djangoec2
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=webapp
      - POSTGRES_PASSWORD=Iu62p46hLnXosIAyPhhP
      - POSTGRES_DB=djangoec2

volumes:
  postgres_data:
